name: Build project

on: [push, pull_request]

jobs:
  # Build project
  build:
    name: Build project
    uses: ./.github/workflows/build.yml
  # Create Release
  release:
    name: Create Release
    needs: build
    uses: ./.github/workflows/release.yml